// packages/solid-v2/src/responsive-image.tsx
import {
  env,
  isResponsiveLayout,
  resolveClassNames,
  resolveHeight,
  resolveSources,
  resolveSrc,
  resolveStyles,
  resolveWidth,
  sourcesSorted as sortSources,
  type ImageData,
} from '@responsive-image/core';
import { isServer, type JSX } from '@solidjs/web';
import { createSignal, omit, onSettled, Show } from 'solid-js';

import './responsive-image.css';

import type { Component } from 'solid-js';

export interface ResponsiveImageArgs {
  src: ImageData;
  size?: number;
  sizes?: string;
  width?: number;
  height?: number;
}

const responsiveImageArgs = [
  'class',
  'src',
  'size',
  'sizes',
  'width',
  'height',
] as const;

export type ResponsiveImageProps = Omit<
  JSX.ImgHTMLAttributes<HTMLImageElement>,
  'src'
> &
  ResponsiveImageArgs;

export const ResponsiveImage: Component<ResponsiveImageProps> = (props) => {
  const [loadedSrc, setLoaded] = createSignal<ImageData | undefined>(undefined);
  const attributes = omit(props, ...responsiveImageArgs);
  const isLoaded = () => loadedSrc() === props.src;

  const responsive = () => isResponsiveLayout(props.width, props.height);

  const width = () =>
    resolveWidth({
      width: props.width,
      height: props.height,
      aspectRatio: props.src.aspectRatio,
      deviceWidths: env.deviceWidths,
      responsive: responsive(),
    });

  const height = () =>
    resolveHeight({
      height: props.height,
      aspectRatio: props.src.aspectRatio,
      width: width(),
    });

  const imgSrc = () => resolveSrc({ src: props.src, width: width() });

  const sources = () =>
    resolveSources({
      src: props.src,
      width: width(),
      sizes: props.sizes,
      size: props.size,
      deviceWidths: env.deviceWidths,
      responsive: responsive(),
    });

  const sourcesSorted = () => sortSources(sources());

  const classNames = () =>
    resolveClassNames({
      src: props.src,
      isLoaded: isLoaded(),
      responsive: responsive(),
      customClass: props['class'] as string,
    });

  const styles = () => resolveStyles(props.src, isLoaded(), isServer);

  // check if src is already loaded (SSR) and update state so LQIP options are removed
  // eslint-disable-next-line no-unassigned-vars --  false positive
  let imgEl: HTMLImageElement | undefined;
  onSettled(() => {
    if (imgEl?.complete) {
      setLoaded(props.src);
    }
  });

  const img = (
    // When LQIP is used, the key is our src, so when src changes, the img element is recreated to re-apply LQIP styles without having
    // the previous src visible (<img> is a stateful element!). Without LQIP, reuse existing DOM.
    // See also https://github.com/simonihmig/responsive-image/issues/1583#issuecomment-3315142391
    <Show when={props.src} keyed={!!props.src.lqip as false}>
      <img
        width={width()}
        height={height()}
        class={classNames().join(' ')}
        loading="lazy"
        decoding="async"
        srcset={
          props.src.imageTypes === 'auto'
            ? // auto format assumes only one entry in sources
              sources()[0]?.srcset
            : undefined
        }
        src={imgSrc()}
        {...attributes}
        data-ri-lqip={props.src.lqip?.attribute}
        style={styles()}
        ref={imgEl}
        // Solid v2: on:load → onLoad (native listener for non-delegated load event)
        onLoad={() => setLoaded(props.src)}
      />
    </Show>
  );

  if (props.src.imageTypes === 'auto') {
    return img;
  }

  return (
    <picture>
      {sourcesSorted().map((s) => (
        <source srcset={s.srcset} type={s.mimeType} sizes={s.sizes} />
      ))}
      {img}
    </picture>
  );
};

// packages/wc/src/responsive-image.ts
import {
  env,
  getValueOrCallback,
  isResponsiveLayout,
  resolveHeight,
  resolveSources,
  resolveSrc,
  resolveWidth,
  sourcesSorted as sortSources,
  type ImageData,
} from '@responsive-image/core';
import { css, html, LitElement, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { type ClassInfo, classMap } from 'lit/directives/class-map.js';
import { ifDefined } from 'lit/directives/if-defined.js';
import { keyed } from 'lit/directives/keyed.js';
import { ref } from 'lit/directives/ref.js';
import { type StyleInfo, styleMap } from 'lit/directives/style-map.js';

@customElement('responsive-image')
export class ResponsiveImage extends LitElement {
  static styles = css`
    .ri-img {
      background-size: cover;
    }

    .ri-responsive {
      width: 100%;
      height: auto;
    }

    .ri-fixed,
    .ri-responsive {
      content-visibility: auto;
    }
  `;

  @property({ type: Object }) src!: ImageData;

  @property({ type: Number }) size?: number;

  @property({ type: String }) sizes?: string;

  @property({ type: Number }) width?: number;

  @property({ type: Number }) height?: number;

  @property({ type: String }) loading: 'eager' | 'lazy' = 'lazy';

  @property({ type: String }) decoding: 'async' | 'sync' | 'auto' = 'async';

  @property({ type: String }) fetchPriority?: 'high' | 'low' | 'auto';

  @property({ type: String }) crossOrigin?: 'anonymous' | 'use-credentials';

  @property({ type: String })
  referrerPolicy?:
    | 'no-referrer'
    | 'no-referrer-when-downgrade'
    | 'origin'
    | 'origin-when-cross-origin'
    | 'same-origin'
    | 'strict-origin'
    | 'strict-origin-when-cross-origin'
    | 'unsafe-url';

  @property({ type: String }) alt = '';

  @state()
  private loadedSrc?: ImageData;

  get complete(): boolean {
    return this.loadedSrc === this.src;
  }

  get responsive(): boolean {
    return isResponsiveLayout(this.width, this.height);
  }

  get sources() {
    return resolveSources({
      src: this.src,
      width: this.imgWidth,
      sizes: this.sizes,
      size: this.size,
      deviceWidths: env.deviceWidths,
      responsive: this.responsive,
    });
  }

  get sourcesSorted() {
    return sortSources(this.sources);
  }

  get imgWidth(): number | undefined {
    return resolveWidth({
      width: this.width,
      height: this.height,
      aspectRatio: this.src.aspectRatio,
      deviceWidths: env.deviceWidths,
      responsive: this.responsive,
    });
  }

  get imgHeight(): number | undefined {
    return resolveHeight({
      height: this.height,
      aspectRatio: this.src.aspectRatio,
      width: this.imgWidth,
    });
  }

  get imgSrc(): string | undefined {
    return resolveSrc({ src: this.src, width: this.imgWidth });
  }

  checkAlreadyLoaded(el?: HTMLImageElement) {
    if (el?.complete) {
      this.loadedSrc = this.src;
    }
  }

  render(): unknown {
    const { lqip, imageTypes } = this.src;

    if (lqip?.class) {
      throw new Error(
        "Using LQIP with a class name is not supported in @responsive-image/wc, as globals styles will not work with web components and Shadow DOM. Use the `styles: 'inline'` option in your build plugin config.",
      );
    }

    const classes: ClassInfo = {
      'ri-img': true,
      'ri-responsive': this.responsive,
      'ri-fixed': !this.responsive,
      ...(lqip?.class && !this.complete
        ? { [getValueOrCallback(lqip.class)]: true }
        : {}),
    };

    const styles: StyleInfo = this.complete
      ? {}
      : {
          ...(lqip?.inlineStyles ? getValueOrCallback(lqip.inlineStyles) : {}),
        };

    const _img = html`
      <img
        part="img"
        width=${ifDefined(this.imgWidth)}
        height=${ifDefined(this.imgHeight)}
        class=${classMap(classes)}
        loading=${this.loading}
        style=${styleMap(styles)}
        srcset=${ifDefined(
          imageTypes === 'auto'
            ? // auto format assumes only one entry in sources
              this.sources[0].srcset
            : undefined,
        )}
        src=${ifDefined(this.imgSrc)}
        alt=${this.alt}
        decoding=${this.decoding}
        crossorigin=${ifDefined(this.crossOrigin)}
        fetchpriority=${ifDefined(this.fetchPriority)}
        referrerpolicy=${ifDefined(this.referrerPolicy)}
        data-ri-lqip=${ifDefined(lqip?.attribute)}
        @load=${(event: Event) => {
          this.loadedSrc = this.src;
          this.dispatchEvent(new Event(event.type, event));
        }}
        @error=${(event: Event) => {
          this.dispatchEvent(new ErrorEvent(event.type, event));
        }}
        @abort=${(event: Event) => {
          this.dispatchEvent(new Event(event.type, event));
        }}
        ${ref(this.checkAlreadyLoaded as (el?: Element) => void)}
      />
    `;

    // When LQIP is used, the key is our src, so when src changes, the img element is recreated to re-apply LQIP styles without having
    // the previous src visible (<img> is a stateful element!). Without LQIP, reuse existing DOM.
    // See also https://github.com/simonihmig/responsive-image/issues/1583#issuecomment-3315142391
    const img = keyed(this.src.lqip && this.src, _img);

    if (imageTypes === 'auto') {
      return img;
    }

    return html`
      <picture>
        ${this.sourcesSorted.map(
          (s) =>
            html`<source
              srcset=${s.srcset}
              type=${ifDefined(s.mimeType)}
              sizes=${s.sizes ?? nothing}
            />`,
        )}
        ${img}
      </picture>
    `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'responsive-image': ResponsiveImage;
  }
}
